datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: "jdbc:postgresql://containers-us-west-121.railway.app:6159/postgres"

ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true