datasource:
  default: ${APP_ENV}
  development:
    username: ""
    password: ""
    url: "jdbc:h2:./database"

ebean:
  development:
    migration:
      run: true
#  production:
#    migration:
#      run: true