# Настройки ORM
datasource:
  # Задаём базу данных, к которой будет происходить подключение
  db:
    username: ""
    password: ""
    url: "jdbc:h2:./hexlet"

#ebean:
#  development:
#    migration:
#      run: true
#  production:
#    migration:
#      run: true